export type SuggestionCategory =
  | "metadata"
  | "schema"
  | "internal_linking"
  | "locality_page"
  | "performance"
  | "image_optimization"
  | "content_quality"
  | "accessibility"
  | "structured_data"
  | "sitemap_robots";

export type SuggestionImpact = "low" | "medium" | "high";
export type SuggestionRisk = "low" | "medium" | "high";

/**
 * A single piece of MEASURED evidence behind a suggestion. Evidence is produced
 * deterministically by the deficit detector from crawl / Lighthouse / geo data —
 * it is never generated by the LLM. This is what makes a suggestion a "deficit
 * with proof" rather than a consultant's recommendation.
 */
export interface SuggestionEvidence {
  /** Which measurement produced this evidence. */
  source: "crawl" | "lighthouse" | "geo";
  /** Human-readable, specific: e.g. "unused-javascript: 79 KiB potential savings". */
  detail: string;
  /** The page/URL the measurement was taken on, when applicable. */
  url?: string;
  /**
   * When the measurement was taken (epoch ms). Completes the provenance trail so
   * a customer asking "why did Syntra suggest this?" gets source + page + what
   * was measured + when.
   */
  detectedAt?: number;
}

/**
 * A deficit detected deterministically from the audit data, before the LLM ever
 * sees it. The orchestrator ranks and phrases findings into Suggestions but may
 * not alter `evidence` — so every shipped suggestion is backed by real numbers.
 */
export interface Finding {
  category: SuggestionCategory;
  /** Deficit-centric statement, e.g. "No FAQPage schema on /whatsapp-os". */
  issue: string;
  evidence: SuggestionEvidence[];
  /**
   * How sure we are this deficit is real, 0..1. Direct DOM/Lighthouse
   * observations are ~0.95-0.99 (a tag is present or it isn't); inferred
   * findings that combine multiple signals (locality demand) are lower because
   * they have more moving parts. Derived deterministically — never LLM-set.
   */
  confidence: number;
  expectedImpact: SuggestionImpact;
  risk: SuggestionRisk;
  /** Deterministic priority seed (0..100); the orchestrator may adjust it. */
  baseScore: number;
  /** Best-effort default phrasing the orchestrator can refine. */
  suggestedTitle: string;
  suggestedImplementation: string;
  /** Best-effort target files inferred from crawled routes. */
  targetFiles: string[];
  geoContext?: GeoSuggestionContext;
}

export interface Suggestion {
  id: string;
  runId: string;
  category: SuggestionCategory;
  title: string;
  /** The deficit this fixes, deficit-centric. */
  issue: string;
  /** Measured proof of the deficit. Never LLM-invented. */
  evidence: SuggestionEvidence[];
  /** How sure we are the deficit is real, 0..1. Derived from how it was observed. */
  confidence: number;
  /** Short human summary (kept for back-compat + list density). */
  description: string;
  /** Why it matters / why this impact level. */
  rationale: string;
  /**
   * Business-aware enrichment, added by the Enrichment agent AFTER the deficit is
   * found. These EXPLAIN an existing finding for THIS business — they never
   * create or alter evidence. `whyItMatters` ties the gap to the site's
   * audience/market/page intent; `businessImpact` names the concrete outcome
   * affected (organic traffic, qualified leads, AI-answer citation, share CTR,
   * topical authority). Optional: empty when enrichment is unavailable, so the
   * card degrades to Issue → Evidence → Implementation.
   */
  whyItMatters?: string;
  businessImpact?: string;
  /** Concrete fix the Code Modification agent will implement. */
  implementation: string;
  expectedImpact: SuggestionImpact;
  risk: SuggestionRisk;
  priorityScore: number;
  targetFiles: string[];
  geoContext?: GeoSuggestionContext;
  status: SuggestionStatus;
  dispatchJobId: string | null;
  prNumber: number | null;
}

export type SuggestionStatus =
  | "proposed"
  | "selected"
  | "dispatched"
  | "implemented"
  | "validated"
  | "rejected"
  | "failed";

export interface GeoSuggestionContext {
  locality: string;
  city: string;
  landmarks: string[];
  searchIntents: string[];
  keywordCluster: string[];
}
